name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get install -y libpam0g-dev

      - name: Build
        run: make

      - name: Test
        run: make test
